title: Cloud4Research
description: >- # this means to ignore newlines until "baseurl:"
  An initiative of the TU Delft IT department

# Build settings
theme: "just-the-docs"

defaults:
  - values:
      layout: "default"